---
name: Portfolio

on:
    workflow_dispatch:

permissions:
    pages: write
    id-token: write
    contents: read

jobs:
    deploy :
        runs-on: ubuntu-latest
        environment: 
            name: github-pages
            url: ${{steps.deployment.outputs.page_url}}

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Setup GitHub pages
              uses: actions/configure-pages@v4

            - name: Static code artifacts
              uses: actions/upload-pages-artifact@v3
              with:
                path : "."

            - name: Deploy to GitHub pages
              id: deployment 
              uses: actions/deploy-pages@v4
